FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY main.go .

# Create module inside container
RUN go mod init go-mesh-demo && \
    go mod tidy && \
    go build -o app

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/app .
EXPOSE 8080
CMD ["./app"]