---
- hosts: all
  become: true

  tasks:
    - name: installing apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: copy file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'